### ISSUE TITLE
cocode react 프로젝트 폴더구조에 관한 의견

### ISSUE THREAD

**Issue by YukJiSoo** [connect-foundation/2019-04#105]
일과를 마치고 집에 돌아온 뒤 오늘 작업을 마무리하기위해 vscode를 켜서 우리의 프로젝트에 들어갔습니다.
그런데 약간 불편한 점이 생겨버렸습니다.

사진부터 보시면

![image](https://user-images.githubusercontent.com/30258523/69249533-5e93f480-0bf1-11ea-9c8e-8260dfc0a613.png)

저희는 **page** > **container** > **component** 구조로 UI를 구현하기로 결정했으며
page는 저희 서비스에서 이동하는 page단위,
container는 page를 구성하는 단위,
component는 재사용 가능하며 container를 구성하는 단위로 결정했습니다.

현재 메인 페이지까지 구현이 완료된 상황에서 이정도의 구현물이 생겼고 뭔가 알아보기가 쉽지는 않다라는? 생각이 들었습니다.

그래서 저의 제안은 
`page 단위별로 component와 container에서 depth를 한번 더 들어가는게 어떤가?` 
입니다. 일단 이미지를 보시겠습니다.

![image](https://user-images.githubusercontent.com/30258523/69250275-b8e18500-0bf2-11ea-8658-32bfac42c924.png)

component와 container 디렉토리 구조를 보시면 Common과 page별로 depth를 한번 더 들어간 것을 보실 수 있습니다.

제가 생각하는 이렇게 하면서 얻을 수 있는 장점으로는
1. 한눈에 어떤 컴포넌트가 어느 page에서 사용되는지 확인할 수 있다.
2. 관리가 용이하다.

정도로 생각합니다.

그전에 디렉토리 구조 이야기하면서 다른 팀원분에게서 나왔던 이야기 인 것 같은데
개발을 실제로 시작해보니 확실히 와닿는것 같아요.

**Comment by hzoou** [comment]
전 좋아요! 제가 이전에 제안했던 내용이네요.
페이지 별로 관리하면 depth가 깊어질 수는 있겠지만 관리하기에 훨씬 편리하다고 생각합니다.
저는 완전 찬성!

**Comment by BasilToast** [comment]
네 저도 찬성입니다.
사실 지금 import하면서도 벌써 헷갈리기 시작하는데 저런식으로 구분이 조금 더 세분화 되는것이 편할것같아요 :)

**Comment by lallaheeee** [comment]
저도 좋아요! 컴포넌트나 컨테이너에서 페이지 별로 한번 더 분류하면 관리가 더 수월할 거 같다는 의견에 찬성!

**Comment by YukJiSoo** [comment]
넵 그러면 오늘까지 기능 구현 완료하고 이번 주 데모를 위한 마무리 한 뒤에
전반적인 리팩토링 시간을 가지면서 다 같이 구조를 보면 좋을 것 같아요 :)
