### ISSUE TITLE
client-side version의 변천사를 보여주는 History page가 있으면 어떨까요?

### ISSUE THREAD

**Issue by YukJiSoo** [connect-foundation/2019-04#135]
우리 프로젝트의 중점은 client side build이지요!
우리가 세웠던 build 기능의 발전은 3단계로 이루어졌으면 좋다고 이야기가 나왔었습니다.

|  <center>version</center> |  <center>기능</center> |
|:--------:|:--------:|
|**1** | <center>하나의 React file만 build, dependency 추가 불가</center> |
|**2** | <center>여러 개의 React file build 가능, dependency 추가 불가</center> |
|**3** | <center>여러 개의 React file build 가능, dependency 추가 가능</center> |

위와 같은 상태로 우리의 기능이 발전했으면 좋겠다는 이야기가 있었고 현재 version1은 구현이 완료된 상태이고 배포까지 되어있는 상태입니다!

저는 Header에 History category를 추가하여 저희 기능의 변천사를 보여주는 page가 있으면 저희의 기술력(?)을 더 자랑할 수 있을 것 같다고 생각했어요.

대략 한번 그려 보았는데,
![image](https://user-images.githubusercontent.com/30258523/69490802-d56e0d80-0ecf-11ea-8497-9c7ff7cfc944.png)
Header에 저렇게 History category가 추가되고

![image](https://user-images.githubusercontent.com/30258523/69490805-e28afc80-0ecf-11ea-9f90-e731853e88d1.png)
History page에서는 우리의 변천사(?)를 보여주도록?

하는 것이 어떨까 생각이 났습니다!

**Comment by hzoou** [comment]
어떨까 제안하셔놓고 이미 코드를 짜버리시다니 .....!
하지만 전 찬성이라 좋습니다.

**Comment by BasilToast** [comment]
찬성입니다 :)
