### ISSUE TITLE
네트워크 로직 커스텀 훅으로 분리 제안 🔥

### ISSUE THREAD

**Issue by lallaheeee** [connect-foundation/2019-04#151]
안녕하세요 친애하고 친애하는 팀원여러분
클라이언트에서 대시보드 페이지에서 사용자별 프로젝트 목록을 조회하는 API를 구현하려고 공부를 하다가, 
커스텀 훅에 대해서 알게됐습니다. 

### ⚡️ 왜 필요한가?

서버에 데이터를 요청하거나, 서버에 데이터 수정을 요청하는 네트워크 로직 부분을 커스텀 훅으로 분리하면 
뷰 이외의 로직을 분리함으로서 중복을 없애고 재사용할 수 있고 사이드 이펙트도 줄일 수 있습니다!   

##### 예시

```js
    import { useState, useEffect } from 'react';
    
    const useFetch = (cb, url) => {
    	const [loading, setLoading] = useState(false);
    
    	const fetchInitialData = async () => {
    		setLoading(true);
    		const response = await fetch(url);
    		const initialData = await response.json();
    		cb(initialData);
    		setLoading(false);
    	};
    
    	useEffect(() => {
    		fetchInitialData();
    	}, []);
    
    	return loading;
    };
    
    export { useFetch };
```

[크롱님의 커스텀 훅 강의](https://www.youtube.com/watch?v=vKllPC06al0&list=PLAHa1zfLtLiMukrBDWr-o0q-At7oARwXv&index=2) 에 나온 코드입니다.

위의 코드와 아래의 참고를 참고하여,

| METHOD | NAME      |
| ------ | --------- |
| POST   | usePost   |
| GET    | useGet    |
| PATCH  | usePatch  |
| DELETE | useDelete |

저희만의 커스텀 훅을 도입해보아요 

### 📌 참고

[[React] React Hooks, axios를 활용하여 data fetch #2](https://angelxtry.github.io/React-Hooks-Axios-Fetch-03/)
[[React] React Hooks, axios를 활용하여 data fetch #3](https://angelxtry.github.io/React-Hooks-Axios-Fetch-03/)

**Comment by BasilToast** [comment]
좋은 아이디어인것같습니다 :)
잘 정리해주셔서 보기가 편하네요 :musical_note: 
감사합니다 :rainbow:

**Comment by YukJiSoo** [comment]
좋아여 저희가 정한 상태관리 프로세스에 추가되어 같이 사용되면 정말 좋을 것 같네요!

**Comment by hzoou** [comment]
좋아요!
