### ISSUE TITLE
window 환경에서 랜더링의 차이

### ISSUE THREAD

**Issue by BasilToast** [connect-foundation/2019-04#172]
윈도우 환경에서 AboutUs가 다르게 랜더링 되는 현상이 발생합니다.

![image](https://user-images.githubusercontent.com/33782602/69817306-a47a3980-123d-11ea-941c-4ebce41cfcc2.png)

추후 시간이된다면 수정하는게 어떨까요?

**Comment by hzoou** [comment]
하겠습니다..! 그런데 화면 비율 100퍼센트로 사용해주시라구요 ㅡㅅㅡ

**Comment by BasilToast** [comment]
죄송합니다.. ㅠㅠ
