### ISSUE TITLE
[ BUG ] 버튼이 안보이는 현상

### ISSUE THREAD

**Issue by happydhKim** [connect-foundation/2019-04#231]
<img width="1440" alt="스크린샷 2019-12-06 오후 2 50 23" src="https://user-images.githubusercontent.com/20928548/70299314-e572df00-1837-11ea-9b2c-fd559a9977b2.png">

### 버그 이슈

버튼을 생성했는데 보이지가 않습니다.

수정부탁드립니다.

**Comment by hzoou** [comment]
버튼에 글로벌 스타일이 흰색으로 적용되어있어 나타나는 현상으로 보입니다!
수정하겠습니다 :)

**Comment by hzoou** [comment]
해당 버그 수정되었습니다 !! :)
