### ISSUE TITLE
[버그] 첫 화면 접속 후  코드실행 오류 노출

### ISSUE THREAD

**Issue by crongro** [connect-foundation/2019-04#232]
코드에 버그가 없는 상태이지만 오른쪽에 아래 내용이 나옵니다.

'TypeError: Cannot read property 'contents' of undefined'

**Comment by hzoou** [comment]
배포 중 생긴 이슈로 해결중에 있습니다..!

**Comment by hzoou** [comment]
해당 버그 해결되었습니다! 감사합니다 :)
