### ISSUE TITLE
[ BUG ] UI 오류

### ISSUE THREAD

**Issue by teihong93** [connect-foundation/2019-04#233]
<img width="251" alt="b" src="https://user-images.githubusercontent.com/52785648/70300339-99756980-183a-11ea-9cd9-66e6926f3ff3.png">
- 로그인 후 프로필 버튼 클릭시 UI 꺠짐(클릭 안됨)

**Comment by BasilToast** [comment]
에러를 출력하는 overlay와 겹쳐 발생한 문제로 판단됩니다.
수정하겠습니다 :)
감사합니당

**Comment by hzoou** [comment]
해당 버그 해결되었습니다! 감사합니다 :)
