### ISSUE TITLE
[BUG] SERACH DEPENDENCY 클릭 시 블록

### ISSUE THREAD

**Issue by doong-jo** [connect-foundation/2019-04#268]
- SERACH DEPENDENCY 클릭 시 아래 Input이 블록 잡힙니다.
<img width="341" alt="스크린샷 2019-12-13 오후 3 02 28" src="https://user-images.githubusercontent.com/22005861/70773050-ad304b00-1db9-11ea-9e69-bd7fcc264041.png">

**Comment by lallaheeee** [comment]
제보 감사합니다 ~ 해당 블록이 잡히지 않도록 반영했습니다!
