### ISSUE TITLE
코드를 저장 할 떄마다 가입이 안되었다고 에러가 뜹니다

### ISSUE THREAD

**Issue by riverandeye** [connect-foundation/2019-04#269]
![image](https://user-images.githubusercontent.com/41494099/70773763-ab678700-1dbb-11ea-8838-8b6a0f0c1a5f.png)

응원합니다 코코드!

**Comment by lallaheeee** [comment]
관훈님 제보와 응원 감사합니다 ^^ 해당 에러는 로그인이 하지 않은 사용자가 프로젝트를 저장할 때 발생하는 에러였고, 
이제는 로그인하지 않아도 저장할 수 있도록 반영했습니다. 관훈님 제보 덕분에 힘이 납니다 이번 한 주도 화이팅하세요 ^-^
