### ISSUE TITLE
[2019/11/12] 회의 

### ISSUE THREAD

**Issue by lallaheeee** [connect-foundation/2019-04#56]
1. component 단위

     ~~[React로 사고하기](https://ko.reactjs.org/docs/thinking-in-react.html) 읽어오기 ~~
    => 네이밍은 material의 컴포넌트대로 하는 걸로.. 단위는 짝코딩하면서.. ?! 

#### NoSql의 컬렉션 단위 

```
유저 :  {
    ,,,
    프로젝트:  {
        {
                ,,, 
                파일:  { } 
        }
}
```
vs
```
유저: { }
프로젝트: { }
파일: { }
```

#### REST API에서 쿼리 스트링의 용도
path, 쿼리스트링

`/api/v1/projects?user_id=hzoou`
vs
`/api/v1/users/:user_id/projects`

**Comment by lallaheeee** [comment]
DB 모델링 
[자료]

**Comment by lallaheeee** [comment]
### REST API에서 쿼리 스트링의 용도 (feat. @YukJiSoo )


![image](https://user-images.githubusercontent.com/22452742/68676356-36771680-059d-11ea-8ace-16151a30335c.png)


스택오버플로우에서 이미 외국인들이 궁금했네여!!

따봉많이받은 댓글을 요약하자면
`path` 는 **특정 자원 식별**에
`query string` 은 자원을 **정렬/필터링** 할 때 사용한다고 합니다 

약간 저희 프로젝트에서는 코에 걸면 코걸이 귀에 걸면 귀걸이가 되는···.

```
유저의 프로젝트 리스트를 가져오라 (특정 자원 식별)
vs
프로젝트를 유저id로 필터링한다 (필터링)
```

https://stackoverflow.com/questions/30967822/when-do-i-use-path-params-vs-query-params-in-a-restful-api

**Comment by lallaheeee** [comment]
저희도 고민을 위키에 잘 정리해 보면 어떨까요?! 

https://www.notion.so/5e63884f0f03417d810ad97d30f58d22

**Comment by lallaheeee** [comment]
#  NoSql의 컬렉션 단위 💥🥊

MongoDB에서 운영 중인 블로그에 다음과 같은 포스팅이 있습니다.
[6 rules of thumb for mongodb schema design part 1](https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-1)
[6 rules of thumb for mongodb schema design part 2](https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-1)
[6 rules of thumb for mongodb schema design part 3](https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-1)

이 글을 한글로 요약한 블로그입니다
[MongoDB 스키마 디자인을 위한 6가지 규칙 요약](https://edykim.com/ko/post/summary-of-six-rules-for-designing-a-mongodb-schema/)


그래서 또 6가지 원칙을 기술하자면
![image](https://user-images.githubusercontent.com/22452742/68692159-55cf6d00-05b8-11ea-8d58-38c0ee04546e.png)


##### 저희 서비스의 데이터 접근 패턴
0. 유저가 가지고 있는 프로젝트 리스트를 보여줘야합니다
1.  초기 프로젝트 정보를 전부 읽어와야합니다. 그 후 프로젝트에 대한 읽기는 없습니다(?). 
2. `ctrl+s` 를 눌러 수정 후 저장하면 해당 파일 하나만 갱신이 됩니다.

#### 그래서  
위의 글에 따르면, 저희 프로젝트에는 `One-to-Many` 가 적합하다고 생각합니다. 

```
// 편의상 ObjectID는 2-byte로 작성, 실제는 12-byte
// parts
{
  _id: ObjectID('AAAA'),
  partno: '123-aff-456',
  name: 'Awesometel 100Ghz CPU',
  qty: 102,
  cost: 1.21,
  price: 3.99
}

// products
{
  name: 'Weird Computer WC-3020',
  manufacturer: 'Haruair Eng.',
  catalog_number: 1234,
  parts: [
    ObjectID('AAAA'),
    ObjectID('DEFO'),
    ObjectID('EJFW')
  ]
}
```

```
// category_number를 기준으로 product를 찾음
> product = db.products.findOne({catalog_number: 1234});
// product의 parts 배열에 담긴 모든 parts를 찾음
> product_parts = db.parts.find({_id: { $in : product.parts } } ).toArray() ;
```

**Comment by YukJiSoo** [comment]
1시부터 진행될 회의에서 개발환경셋팅 마무리!

**Comment by BasilToast** [comment]
테스트를 어느타이밍에 할지에 대한 토의가 필요할 것 같습니다.

**Comment by YukJiSoo** [comment]
**팩트 싸움 1번**
[작은 컬렉션 단위로 분리] 승리

**팩트 싸움 2번**
[쿼리스트링] 승리

**Comment by hzoou** [comment]
브랜치 나눌때 크게 서비스를 어떤 식으로 분리할 것인지 토의가 필요할 것 같습니다.
