### ISSUE TITLE
[19/11/13] 2차 스프린트 회의

### ISSUE THREAD

**Issue by lallaheeee** [connect-foundation/2019-04#62]
API문서, DB 모델링 기반으로 백로그 추출

**Comment by hzoou** [comment]
기존에 작성했던 백로그에 우선순위를 부여해야합니다.

**Comment by hzoou** [comment]
마일스톤 작성

**Comment by lallaheeee** [comment]
1. 데모 데이
- 데모 시연 2명 선정
- 기술공유 2명 선정 

2. 온라인 코드 리뷰를 받을 수 있을까요,, 큼큼,,

**Comment by lallaheeee** [comment]
- [ ] RESTful APIㅇㅔ 대해 각각 uri 적어온 후 투표하기

**Comment by lallaheeee** [comment]
매일 기능을 조금씩 분배를 해서 구현하고, 

웹팩에 대한 리서치와 공유를 같이 하고,
매일 빌더에 대한 고민을 하고 공유를 해야할것 같다.
얼추 우리만의 빌드 과정이 잡혀졌다. 그러면 백로그에 넣어서 분배를 하자
