### ISSUE TITLE
[19/11/15] 회의

### ISSUE THREAD

**Issue by lallaheeee** [connect-foundation/2019-04#77]
- [x] 데모 시연 준비
- [x] 기술 공유 준비

**Comment by hzoou** [comment]
api uri 논의

**Comment by lallaheeee** [comment]
METHOD | URI | FEAT
-- | -- | --
GET | /api/users/:username/repos | 내 프로젝트 목록 조회
GET | /api/repos/:owner/:repo | 프로젝트 정보 조회

**Comment by BasilToast** [comment]
METHOD | URI | FEAT
-- | -- | --
GET | /api/users/:username/repos | 내 프로젝트 목록 조회
GET | /api/users/:username/:repo | 프로젝트 정보 조회

**Comment by hzoou** [comment]
METHOD | URI | FEAT
-- | -- | --
GET | /api/v1/users/:username/projects | 내 프로젝트 목록 조회
POST |  /api/v1/projects/(:owner/) | 프로젝트 생성
GET | /api/v1/projects/(:owner/):projecs_id | 프로젝트 정보 조회
POST | /api/v1/projects/:project_id/files | 파일 생성
GET | /api/v1/projects/:project_id/files/:file_id | 파일 조회

**Comment by YukJiSoo** [comment]
METHOD | URI | FEAT
-- | -- | --
GET | /api/projects/:username | 내 프로젝트 목록 조회
GET | /api/projects/:username/:repo | 프로젝트 정보 조회

**Comment by hzoou** [comment]
#### 결론
METHOD | URI | FEAT
-- | -- | --
GET | /api/users/:username/projects | 내 프로젝트 목록 조회
POST | /api/projects| 프로젝트 생성
GET | /api/projects/:project_id | 프로젝트 정보 조회
POST | /api/projects/:project_id/files | 파일 생성
GET | /api/projects/:project_id/files/:file_id | 파일 조회
