### ISSUE TITLE
[19/11/19] 리액트 컴포넌트 폴더 구조

### ISSUE THREAD

**Issue by BasilToast** [connect-foundation/2019-04#88]
## 컴포넌트 폴더 구조
```
.
└── src
    ├── components
    │   └── GlobalStyle
    │       └── index.js
    ├── containers
    └── pages
        ├── DashBoard
        ├── Home
        ├── index.js
        └── Project
```

**Comment by YukJiSoo** [comment]
- page는 app의 페이지 단위를 의미한다
- container는 page를 구성하는 큰 덩어리이다. component로 구성되어 있다.
- component는 재사용 가능한 단위이다. component들을 조합해서 container를 구성한다.

**Comment by YukJiSoo** [comment]
**component naming에 관한 제안**
naming에 관하여 협의하기가 어렵기 때문에 material-ui의 naming을 따르는 것은 어떨까 싶습니다.
이로 인해 naming에 관한 의견일치 시간을 줄일 수 있을 것으로 예상됩니다.
