### ISSUE TITLE
React 개발 시 Story Book을 사용 제안

### ISSUE THREAD

**Issue by BasilToast** [connect-foundation/2019-04#91]
작성한 컴포넌트들을 보다 쉽게 확인하고, 테스트하기 위해 스토리북을 사용하면 좋을것 같습니다.

**Comment by lallaheeee** [comment]
네! 제가 개인 레포에서 프로토타입 만들고 공유하겠습니다!

**Comment by YukJiSoo** [comment]
개발할때 편할거 같고 UI 문서화도 가능해서 좋을 것 같아요!
